"""Diagnostic plotting utilities for quadrupole estimates and phase advances."""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from tmom_recon import build_twiss_from_measurements

from aba_optimiser.accelerators import LHC
from aba_optimiser.config import PROJECT_ROOT
from aba_optimiser.mad import GradientDescentMadInterface
from aba_optimiser.measurements.squeeze_helpers import (
    ANALYSIS_DIRS,
    BETABEAT_DIR,
    MODEL_DIRS,
    get_measurement_date,
    get_or_make_sequence,
    get_results_dir,
    load_estimates,
)

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

import argparse
import json
import logging

import matplotlib.pyplot as plt

LOGGER = logging.getLogger(__name__)


def load_energy_and_deltap_from_metadata(beam: int, squeeze_step: str) -> tuple[float, float]:
    """Load beam energy and machine deltap from the temp analysis metadata generated by optimisation."""
    metadata_file = (
        PROJECT_ROOT
        / f"temp_analysis_squeeze_b{beam}_{squeeze_step.replace('.', '_')}"
        / "metadata.json"
    )
    if not metadata_file.exists():
        raise FileNotFoundError(
            f"Metadata not found at {metadata_file}. Run optimisation first or regenerate without --skip-reload."
        )
    with metadata_file.open("r") as f:
        metadata = json.load(f)
    energy = float(metadata.get("energy", 450.0))
    deltap = float(metadata.get("machine_deltap", 0.0))
    energy = 450
    deltap = 0.0
    return energy, deltap


def get_twiss_without_errors(
    accelerator: LHC,
    just_bpms: bool,
    estimated_magnets: dict[str, float] | None = None,
    tune_knobs_file: Path | None = None,
    corrector_file: Path | None = None,
    deltap: float = 0.0,
) -> pd.DataFrame:
    """Get twiss data from a model with optional tune knobs and estimated magnets."""
    mad = GradientDescentMadInterface(
        accelerator,
        corrector_strengths=corrector_file,
        tune_knobs_file=tune_knobs_file,
    )
    if estimated_magnets is not None:
        mad.update_knob_values(estimated_magnets)
        # mad.set_magnet_strengths(estimated_magnets)
    return mad.run_twiss(deltap=deltap, observe=int(just_bpms))


def get_fullring_twiss(
    accelerator: LHC,
    estimated_magnets: dict[str, float] | None = None,
    tune_knobs_file: Path | None = None,
    corrector_file: Path | None = None,
    deltap: float = 0.0,
) -> pd.DataFrame:
    """Get full-ring twiss data at BPMs with column names aligned to measurement data."""
    twiss = get_twiss_without_errors(
        accelerator,
        just_bpms=True,
        estimated_magnets=estimated_magnets,
        tune_knobs_file=tune_knobs_file,
        corrector_file=corrector_file,
        deltap=deltap,
    )
    return twiss.rename(columns={"mu1": "mux", "mu2": "muy", "beta11": "betx", "beta22": "bety"})


def find_true_values(
    accelerator: LHC,
    estimates: dict[str, dict[str, float]],
    tune_knobs_file: Path,
    corrector_file: Path | None = None,
) -> dict[str, dict[str, float]]:
    """Find true quadrupole values from the sequence file with tune knobs applied."""
    mad = GradientDescentMadInterface(
        accelerator,
        tune_knobs_file=tune_knobs_file,
        corrector_strengths=corrector_file,
    )
    actual = {}
    for arc, mags in estimates.items():
        actual[arc] = {}
        for mag in mags:
            # elem_name, property_name = mag.rsplit(".", 1)
            # true_k1 = mad.mad.MADX[elem_name][property_name]
            actual[arc][mag] = mad.mad.loaded_sequence[mag]
    return actual


def plot_quad_diffs(
    estimates: dict,
    actual: dict,
    squeeze_step: str,
    results_dir: Path,
    fullring: bool = False,
    accelerator: LHC | None = None,
) -> None:
    """Plot quadrupole differences.

    In full-ring mode, strengths are expected under the ``Arc 1`` header and plotted
    in a single panel.
    """
    if fullring:
        arc_key = "Arc 1"
        if arc_key not in estimates or arc_key not in actual:
            raise KeyError(
                "Full-ring mode expects all strengths under 'Arc 1' in both estimates and actual values."
            )

        mags = list(estimates[arc_key].keys())
        rel_diffs = [
            abs(estimates[arc_key][m] - actual[arc_key][m])
            / abs(actual[arc_key][m])
            * 100
            * np.sign(actual[arc_key][m])
            for m in mags
        ]

        # Separate quads and bends+others
        quads = [m for m in mags if "mq" in m.lower()]
        bends_others = [m for m in mags if "mq" not in m.lower()]

        quad_indices = [mags.index(m) for m in quads]
        bends_others_indices = [mags.index(m) for m in bends_others]

        quad_diffs = [rel_diffs[i] for i in quad_indices]
        bends_others_diffs = [rel_diffs[i] for i in bends_others_indices]

        # Colors for bends_others
        bends_others_colors = []
        for m in bends_others:
            if "mb" in m.lower():
                bends_others_colors.append("blue")
            else:
                bends_others_colors.append("green")

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6))

        # Quadrupoles subplot: if possible, place bars at model s-positions and overlay IP markers.
        if accelerator is not None:
            quad_elems = [m.rsplit(".", 1)[0] for m in quads]
            quad_pos = get_element_positions(accelerator, quad_elems)
            quads_with_pos = [
                (quad_name, quad_pos[quad_name.rsplit(".", 1)[0]])
                for quad_name in quads
                if quad_name.rsplit(".", 1)[0] in quad_pos
            ]
            quads_without_pos = [
                quad_name for quad_name in quads if quad_name.rsplit(".", 1)[0] not in quad_pos
            ]

            if quads_without_pos:
                # If a quadrupole cannot be placed along s, move it to the generic panel.
                bends_others.extend(quads_without_pos)
                bends_others_diffs.extend(
                    [
                        abs(estimates[arc_key][q] - actual[arc_key][q])
                        / abs(actual[arc_key][q])
                        * 100
                        * np.sign(actual[arc_key][q])
                        for q in quads_without_pos
                    ]
                )
                bends_others_colors.extend(["green"] * len(quads_without_pos))
                LOGGER.info(
                    "Moved %d quadrupoles without s-position to 'Bending Magnets & Others' panel.",
                    len(quads_without_pos),
                )

            if quads_with_pos:
                quad_x = [pos for _, pos in quads_with_pos]
                quad_y = [
                    abs(estimates[arc_key][q] - actual[arc_key][q])
                    / abs(actual[arc_key][q])
                    * 100
                    * np.sign(actual[arc_key][q])
                    for q, _ in quads_with_pos
                ]
                ax1.bar(quad_x, quad_y, color="red", width=20.0)
                ax1.set_xlabel("S (m)")
                add_ip_positions_to_plot(ax1, get_ip_positions(accelerator))
            else:
                ax1.text(
                    0.5,
                    0.5,
                    "No quadrupoles with available s-position",
                    transform=ax1.transAxes,
                    ha="center",
                    va="center",
                )
                ax1.set_xticks([])
        else:
            ax1.bar(range(len(quads)), quad_diffs, color="red")
            ax1.set_xticks(range(len(quads)))
            ax1.set_xticklabels([m.split(".")[1] for m in quads], rotation=90)
        ax1.set_title("Quadrupoles")
        ax1.set_ylabel(r"$\Delta k_1 / k_1$ (%)")

        # Bends and others subplot
        ax2.bar(range(len(bends_others)), bends_others_diffs, color=bends_others_colors)
        ax2.set_xticks(range(len(bends_others)))
        ax2.set_xticklabels([m.split(".")[1] for m in bends_others], rotation=90)
        ax2.set_title("Bending Magnets & Others")
        ax2.set_ylabel(r"$\Delta k_0 / k_0$ (%)")

        # Add legend for ax2
        import matplotlib.patches as mpatches

        handles = [
            mpatches.Patch(color="blue", label="Bending magnets"),
            mpatches.Patch(color="green", label="Others"),
        ]
        ax2.legend(handles=handles, loc="upper right")

        plt.tight_layout()
        plt.savefig(results_dir / f"quad_diffs_{squeeze_step}_fullring.png")
        return

    fig, axes = plt.subplots(2, 4, figsize=(20, 10))
    axes = axes.flatten()
    for arc_num in range(1, 9):
        ax = axes[arc_num - 1]
        arc_key = f"Arc {arc_num}"
        if arc_key in estimates:
            mags = list(estimates[arc_key].keys())
            rel_diffs = [
                abs(estimates[arc_key][m] - actual[arc_key][m])
                / abs(actual[arc_key][m])
                * 100
                * np.sign(actual[arc_key][m])
                for m in mags
            ]
            ax.bar(range(len(mags)), rel_diffs)
            ax.set_xticks(range(len(mags)))
            ax.set_xticklabels([m.split(".")[1] for m in mags], rotation=90)
            ax.set_title(f"Arc {arc_num}")
            ax.set_ylabel("Estimated k1")
    plt.tight_layout()
    plt.savefig(results_dir / f"quad_diffs_{squeeze_step}.png")


def get_arc_ranges(beam: int) -> dict[int, tuple[str, str]]:
    """Get arc ranges (start BPM -> end BPM) for each arc.

    Returns dictionary mapping arc number to (start_element, end_element) tuples.
    Arc goes from 13R -> 12L (e.g., Arc 1 goes from IP1 to IP2).
    """
    if beam == 1:
        return {
            1: ("BPM.13R1.B1", "BPM.12L2.B1"),
            2: ("BPM.13R2.B1", "BPM.12L3.B1"),
            3: ("BPM.13R3.B1", "BPM.12L4.B1"),
            # 3: ("BPM.13L3.B1", "BPM.13R3.B1"),
            4: ("BPM.13R4.B1", "BPM.12L5.B1"),
            5: ("BPM.13R5.B1", "BPM.12L6.B1"),
            # 6: ("BPM.13L6.B1", "BPM.13R6.B1"),
            6: ("BPM.13R6.B1", "BPM.12L7.B1"),
            7: ("BPM.13R7.B1", "BPM.12L8.B1"),
            8: ("BPM.13R8.B1", "BPM.12L1.B1"),
        }
    return {
        1: ("BPM.13L1.B2", "BPM.12R2.B2"),
        2: ("BPM.13L2.B2", "BPM.12R3.B2"),
        3: ("BPM.13L3.B2", "BPM.12R4.B2"),
        4: ("BPM.13L4.B2", "BPM.12R5.B2"),
        5: ("BPM.13L5.B2", "BPM.12R6.B2"),
        6: ("BPM.13L6.B2", "BPM.12R7.B2"),
        7: ("BPM.13L7.B2", "BPM.12R8.B2"),
        8: ("BPM.13L8.B2", "BPM.12R1.B2"),
    }


def get_ip_positions(accelerator: LHC) -> dict[str, float]:
    """Get longitudinal positions for IP1..IP8 from a model twiss."""
    mad_iface = GradientDescentMadInterface(accelerator)
    mad_iface.observe_elements(pattern="IP[1-8]$")
    tws = mad_iface.run_twiss()
    return {f"IP{ip}": float(tws.loc[f"IP{ip}", "s"]) for ip in range(1, 9)}


def add_ip_positions_to_plot(ax: plt.Axes, ip_positions: dict[str, float]) -> None:
    """Add dashed vertical lines and labels for interaction points."""
    for ip, pos in ip_positions.items():
        ax.axvline(pos, color="grey", linestyle="--", alpha=0.5)
        ax.text(
            pos,
            ax.get_ylim()[1] * 0.9,
            ip,
            rotation=90,
            verticalalignment="top",
            horizontalalignment="right",
            fontsize=8,
            color="grey",
        )


def get_element_positions(accelerator: LHC, element_names: list[str]) -> dict[str, float]:
    """Get model s-positions for selected lattice elements."""
    mad_iface = GradientDescentMadInterface(accelerator)
    tws = mad_iface.run_twiss(observe=0)
    s_by_name = {str(name).upper(): float(s) for name, s in tws["s"].items()}
    return {name: s_by_name[name.upper()] for name in element_names if name.upper() in s_by_name}


def _normalize_phase(df: pd.DataFrame, mu_cols: tuple[str, str], start_bpm: str) -> pd.DataFrame:
    """Shift phase columns so the chosen start BPM sits at zero."""
    if df.empty:
        return df

    df = df.copy()
    start_row = df.loc[start_bpm] if start_bpm is not None else df.iloc[0]
    df[mu_cols[0]] = df[mu_cols[0]] - start_row[mu_cols[0]]
    df[mu_cols[1]] = df[mu_cols[1]] - start_row[mu_cols[1]]
    return df


def get_twiss_through_arc(
    accelerator: LHC,
    arc_start: str,
    arc_end: str,
    meas_twiss: pd.DataFrame,
    estimated_magnets: dict[str, float] | None = None,
    tune_knobs_file: Path | None = None,
    corrector_file: Path | None = None,
    deltap: float = 0.0,
) -> pd.DataFrame:
    """Get twiss data (phase and beta) through an arc using model with range and beta0 from measurement.

    Args:
        accelerator: Shared accelerator object
        arc_start: Starting element name
        arc_end: Ending element name
        meas_twiss: Twiss from measurement (for beta0 initialization)
        estimated_magnets: Optional magnet strength estimates
        tune_knobs_file: Optional tune knobs file
        corrector_file: Optional corrector strengths file

    Returns:
        DataFrame with phase advances and beta functions at BPM locations
    """
    mad = GradientDescentMadInterface(
        accelerator=accelerator,
        corrector_strengths=corrector_file,
        tune_knobs_file=tune_knobs_file,
    )

    if estimated_magnets is not None:
        mad.update_knob_values(estimated_magnets)

    # Optics at arc start (measurement beta0)
    if arc_start not in meas_twiss.index:
        raise KeyError(
            f"Start BPM {arc_start} not found in measurement twiss; bet/alf are required."
        )
    row = meas_twiss.loc[arc_start]

    # Ensure required optics (beta and alpha) are present and not NaN
    required_cols = ("betx", "bety", "alfx", "alfy", "errbetx", "errbety", "erralfx", "erralfy")
    missing = [c for c in required_cols if c not in row.index or pd.isna(row[c])]
    if missing:
        raise KeyError(
            f"Missing required optics columns at {arc_start}: {missing}. betx/bety/alfx/alfy must be present."
        )

    # Use .get for optional columns so missing ones default to 0.0
    optics = {
        "betx": row["betx"],
        "bety": row["bety"],
        "alfx": row["alfx"],
        "alfy": row["alfy"],
        "dx": row.get("dx", 0.0),
        "dpx": row.get("dpx", 0.0),
        "dy": row.get("dy", 0.0),
        "dpy": row.get("dpy", 0.0),
    }

    optics_err = {
        "betx": row["errbetx"],
        "bety": row["errbety"],
        "alfx": row["erralfx"],
        "alfy": row["erralfy"],
        "dx": row.get("errdx", 0.0),
        "dpx": row.get("errdpx", 0.0),
        "dy": row.get("errdy", 0.0),
        "dpy": row.get("errdpy", 0.0),
    }

    run_twiss_string = f"""
    local B0 = MAD.beta0 {{
        beta11=py:recv(),
                if accelerator is not None:
                    quad_elem_names = [m.rsplit(".", 1)[0] for m in quads]
                    quad_pos = get_element_positions(accelerator, quad_elem_names)
                    quads_with_pos = [(m, quad_pos[m.rsplit(".", 1)[0]]) for m in quads if m.rsplit(".", 1)[0] in quad_pos]
                    if quads_with_pos:
                        quad_x = [pos for _, pos in quads_with_pos]
                        quad_diffs = [
                            abs(estimates[arc_key][m] - actual[arc_key][m])
                            / abs(actual[arc_key][m])
                            * 100
                            * np.sign(actual[arc_key][m])
                            for m, _ in quads_with_pos
                        ]
                        quad_labels = [m.split(".")[1] for m, _ in quads_with_pos]
                    else:
                        quad_x = list(range(len(quads)))
                        quad_labels = [m.split(".")[1] for m in quads]
                else:
                    quad_x = list(range(len(quads)))
                    quad_labels = [m.split(".")[1] for m in quads]
        beta22=py:recv(),
        alfa11=py:recv(),
                if accelerator is not None and quad_x and isinstance(quad_x[0], float):
                    ax1.bar(quad_x, quad_diffs, color="red", width=20.0)
                    ax1.set_xlabel("S (m)")
                    add_ip_positions_to_plot(ax1, get_ip_positions(accelerator))
                else:
                    ax1.bar(range(len(quads)), quad_diffs, color="red")
                    ax1.set_xticks(range(len(quads)))
                    ax1.set_xticklabels(quad_labels, rotation=90)
        dy=py:recv(),
        dpy=py:recv(),
    }}
    twiss_result = twiss {{
        sequence = loaded_sequence,
        range ="{arc_start}/{arc_end}",
        X0 = B0,
        observe = 1,
        deltap = {deltap:.6e},
    }}
    """

    def run_twiss(values: list[float]) -> pd.DataFrame:
        mad.mad.send(run_twiss_string)
        for val in values:
            mad.mad.send(val)
        df = mad.mad.twiss_result.to_df().set_index("name")
        return df.rename(columns={"mu1": "mux", "mu2": "muy", "beta11": "betx", "beta22": "bety"})

    base = run_twiss(list(optics.values()))
    plus = run_twiss([optics[k] + optics_err[k] for k in optics])
    minus = run_twiss([optics[k] - optics_err[k] for k in optics])

    base["mux_err"] = abs(plus["mux"] - minus["mux"]) / 2
    base["muy_err"] = abs(plus["muy"] - minus["muy"]) / 2
    base["betx_err"] = abs(plus["betx"] - minus["betx"]) / 2
    base["bety_err"] = abs(plus["bety"] - minus["bety"]) / 2

    return _normalize_phase(base, ("mux", "muy"), start_bpm=arc_start)


def get_measurement_phase_through_arc(
    meas_twiss: pd.DataFrame,
    arc_start: str,
    arc_end: str,
) -> tuple[pd.DataFrame, list[str]]:
    """Get phase advance through arc from measurement data.

    Args:
        meas_twiss: Twiss from measurement
        arc_start: Starting element name
        arc_end: Ending element name

    Returns:
        DataFrame with relative phase advances
    """
    # Get all BPMs in the arc range
    start_s = meas_twiss.loc[arc_start, "s"]
    end_s = meas_twiss.loc[arc_end, "s"]

    if end_s < start_s:
        arc_bpms = meas_twiss[(meas_twiss["s"] >= start_s) | (meas_twiss["s"] <= end_s)]
    else:
        arc_bpms = meas_twiss[(meas_twiss["s"] >= start_s) & (meas_twiss["s"] <= end_s)]

    if arc_bpms.empty:
        return arc_bpms, []

    candidate_bpms = list(arc_bpms.head(2).index)
    return arc_bpms, candidate_bpms


def plot_phase_advances(
    accelerator: LHC,
    all_estimates: dict,
    analysis_dir: Path,
    squeeze_step: str,
    results_dir: Path,
    tune_knobs_file: Path,
    corrector_file: Path | None,
    beam: int,
    arcs: list[int] | None = None,
    deltap: float = 0.0,
) -> None:
    """Plot phase advance comparison through each arc with four models.

    Args:
        arcs: Optional list of arc numbers to plot. If None, plots all arcs 1-8.
    """
    meas_twiss, _ = build_twiss_from_measurements(
        analysis_dir, include_errors=True, reverse_bpm_order=beam == 2
    )
    meas_twiss.columns = [col.lower() for col in meas_twiss.columns]

    # Get arc ranges
    arc_ranges = get_arc_ranges(beam)

    # Use specified arcs or default to all
    arc_list = arcs if arcs is not None else list(range(1, 9))

    for arc_num in arc_list:
        arc_start, arc_end = arc_ranges[arc_num]
        fig, axes = plt.subplots(2, 2, figsize=(16, 10))

        # Get measurement arc (unnormalized) and candidate BPMs near arc start
        meas_phase_raw, candidate_bpms = get_measurement_phase_through_arc(meas_twiss, arc_start, arc_end)

        # Initial base model (no knobs/estimates) to pick best start BPM by minimal phase error
        def choose_best_start_bpm(candidates: list[str]) -> str:
            best_bpm = candidates[0]
            min_error = float("inf")
            for start_bpm in candidates:
                if start_bpm not in meas_twiss.index:
                    continue
                phase_initial = get_twiss_through_arc(
                    accelerator,
                    start_bpm,
                    arc_end,
                    meas_twiss,
                    estimated_magnets=None,
                    tune_knobs_file=None,
                    corrector_file=None,
                )
                var_x = np.sum((phase_initial["mux_err"]) ** 2)
                var_y = np.sum((phase_initial["muy_err"]) ** 2)
                total_var = var_x + var_y
                if total_var < min_error:
                    min_error = total_var
                    best_bpm = start_bpm
            return best_bpm

        start_bpm = choose_best_start_bpm(candidate_bpms)

        # Normalize measurement to chosen start BPM
        meas_phase = _normalize_phase(meas_phase_raw, ("mux", "muy"), start_bpm=start_bpm)

        # Recompute models using chosen start BPM (shared beta0 and range)
        twiss_basic = get_twiss_through_arc(
            accelerator,
            start_bpm,
            arc_end,
            meas_twiss,
            estimated_magnets=None,
            tune_knobs_file=None,
            corrector_file=None,
        )

        twiss_online = get_twiss_through_arc(
            accelerator,
            start_bpm,
            arc_end,
            meas_twiss,
            estimated_magnets=None,
            tune_knobs_file=tune_knobs_file,
            corrector_file=corrector_file,
        )

        twiss_eff_online = get_twiss_through_arc(
            accelerator,
            start_bpm,
            arc_end,
            meas_twiss,
            estimated_magnets=all_estimates,
            tune_knobs_file=tune_knobs_file,
            corrector_file=corrector_file,
            deltap=deltap,
        )

        # Find common BPMs
        common_bpms = (
            meas_phase.index.intersection(twiss_basic.index)
            .intersection(twiss_online.index)
            .intersection(twiss_eff_online.index)
        )
        if len(common_bpms) == 0:
            logging.warning(f"No common BPMs found in Arc {arc_num}, skipping plot.")
            continue

        def _diff(series: pd.Series, series_err: pd.Series | None, meas: pd.Series, meas_err: pd.Series | None) -> tuple[pd.Series, pd.Series | None]:
            delta = series.loc[common_bpms] - meas.loc[common_bpms]
            if series_err is None and meas_err is None:
                return delta, None
            series_err_vals = series_err.loc[common_bpms] if series_err is not None else 0.0
            meas_err_vals = meas_err.loc[common_bpms] if meas_err is not None else 0.0
            return delta, np.sqrt(series_err_vals**2 + meas_err_vals**2)

        def _rel_diff(
            series: pd.Series,
            series_err: pd.Series | None,
            meas: pd.Series,
            meas_err: pd.Series | None,
        ) -> tuple[pd.Series, pd.Series | None]:
            """Calculate relative difference: (series - meas) / meas * 100 (in percent)"""
            rel_delta = (
                (series.loc[common_bpms] - meas.loc[common_bpms]) / meas.loc[common_bpms] * 100
            )
            if series_err is None and meas_err is None:
                return rel_delta, None
            series_err_vals = series_err.loc[common_bpms] if series_err is not None else 0.0
            meas_err_vals = meas_err.loc[common_bpms] if meas_err is not None else 0.0
            # Error propagation for relative difference
            rel_err = (
                np.sqrt(series_err_vals**2 + meas_err_vals**2) / np.abs(meas.loc[common_bpms]) * 100
            )
            return rel_delta, rel_err

        def _plot(ax, xvals, series, yerr, label, fmt):
            ax.errorbar(
                xvals,
                series,
                yerr=yerr,
                fmt=fmt,
                markersize=3,
                label=label,
                alpha=0.8,
                capsize=2,
            )

        # Phase X
        ax_phase_x = axes[0, 0]
        meas_mux = meas_phase["mux"]
        meas_mux_err = meas_phase.get("errmux")
        base_dx, base_dx_err = _diff(
            twiss_basic["mux"], twiss_basic.get("mux_err"), meas_mux, meas_mux_err
        )
        _plot(
            ax_phase_x,
            meas_phase.loc[common_bpms, "s"],
            base_dx,
            base_dx_err,
            "Base model - meas",
            "s-",
        )
        online_dx, online_dx_err = _diff(
            twiss_online["mux"], twiss_online.get("mux_err"), meas_mux, meas_mux_err
        )
        _plot(
            ax_phase_x,
            meas_phase.loc[common_bpms, "s"],
            online_dx,
            online_dx_err,
            "Model+tunes - meas",
            "^-",
        )
        eff_dx, eff_dx_err = _diff(
            twiss_eff_online["mux"], twiss_eff_online.get("mux_err"), meas_mux, meas_mux_err
        )
        _plot(
            ax_phase_x,
            meas_phase.loc[common_bpms, "s"],
            eff_dx,
            eff_dx_err,
            "Model+tunes+ests - meas",
            "d-",
        )
        ax_phase_x.axhline(0.0, color="k", linewidth=0.8, alpha=0.5)
        ax_phase_x.set_ylabel("Δ Phase X vs meas (2π)")
        ax_phase_x.set_title(f"Arc {arc_num} - Horizontal Phase Δ")
        ax_phase_x.legend(fontsize=8)
        ax_phase_x.grid(visible=True, alpha=0.3)
        ax_phase_x.set_xlabel("S (m)")

        # Phase Y
        ax_phase_y = axes[0, 1]
        meas_muy = meas_phase["muy"]
        meas_muy_err = meas_phase.get("errmuy")
        base_dy, base_dy_err = _diff(
            twiss_basic["muy"], twiss_basic.get("muy_err"), meas_muy, meas_muy_err
        )
        _plot(
            ax_phase_y,
            meas_phase.loc[common_bpms, "s"],
            base_dy,
            base_dy_err,
            "Base model - meas",
            "s-",
        )
        online_dy, online_dy_err = _diff(
            twiss_online["muy"], twiss_online.get("muy_err"), meas_muy, meas_muy_err
        )
        _plot(
            ax_phase_y,
            meas_phase.loc[common_bpms, "s"],
            online_dy,
            online_dy_err,
            "Model+tunes - meas",
            "^-",
        )
        eff_dy, eff_dy_err = _diff(
            twiss_eff_online["muy"], twiss_eff_online.get("muy_err"), meas_muy, meas_muy_err
        )
        _plot(
            ax_phase_y,
            meas_phase.loc[common_bpms, "s"],
            eff_dy,
            eff_dy_err,
            "Model+tunes+ests - meas",
            "d-",
        )
        ax_phase_y.axhline(0.0, color="k", linewidth=0.8, alpha=0.5)
        ax_phase_y.set_ylabel("Δ Phase Y vs meas (2π)")
        ax_phase_y.set_title(f"Arc {arc_num} - Vertical Phase Δ")
        ax_phase_y.legend(fontsize=8)
        ax_phase_y.grid(visible=True, alpha=0.3)
        ax_phase_y.set_xlabel("S (m)")

        # Beta X
        ax_beta_x = axes[1, 0]
        meas_betx = meas_twiss.loc[common_bpms, "betx"]
        meas_betx_err = meas_twiss.loc[common_bpms].get("errbetx")
        base_dbetx, base_dbetx_err = _rel_diff(
            twiss_basic["betx"], twiss_basic.get("betx_err"), meas_betx, meas_betx_err
        )
        _plot(
            ax_beta_x,
            meas_twiss.loc[common_bpms, "s"],
            base_dbetx,
            base_dbetx_err,
            "Base model - meas",
            "s-",
        )
        online_dbetx, online_dbetx_err = _rel_diff(
            twiss_online["betx"], twiss_online.get("betx_err"), meas_betx, meas_betx_err
        )
        _plot(
            ax_beta_x,
            meas_twiss.loc[common_bpms, "s"],
            online_dbetx,
            online_dbetx_err,
            "Model+tunes - meas",
            "^-",
        )
        eff_dbetx, eff_dbetx_err = _rel_diff(
            twiss_eff_online["betx"], twiss_eff_online.get("betx_err"), meas_betx, meas_betx_err
        )
        _plot(
            ax_beta_x,
            meas_twiss.loc[common_bpms, "s"],
            eff_dbetx,
            eff_dbetx_err,
            "Model+tunes+ests - meas",
            "d-",
        )
        ax_beta_x.axhline(0.0, color="k", linewidth=0.8, alpha=0.5)
        ax_beta_x.set_ylabel("Δ β_x / β_x vs meas (%)")
        ax_beta_x.set_title(f"Arc {arc_num} - Horizontal β Δ")
        ax_beta_x.legend(fontsize=8)
        ax_beta_x.grid(visible=True, alpha=0.3)
        ax_beta_x.set_xlabel("S (m)")

        # Beta Y
        ax_beta_y = axes[1, 1]
        meas_bety = meas_twiss.loc[common_bpms, "bety"]
        meas_bety_err = meas_twiss.loc[common_bpms].get("errbety")
        base_dbety, base_dbety_err = _rel_diff(
            twiss_basic["bety"], twiss_basic.get("bety_err"), meas_bety, meas_bety_err
        )
        _plot(
            ax_beta_y,
            meas_twiss.loc[common_bpms, "s"],
            base_dbety,
            base_dbety_err,
            "Base model - meas",
            "s-",
        )
        online_dbety, online_dbety_err = _rel_diff(
            twiss_online["bety"], twiss_online.get("bety_err"), meas_bety, meas_bety_err
        )
        _plot(
            ax_beta_y,
            meas_twiss.loc[common_bpms, "s"],
            online_dbety,
            online_dbety_err,
            "Model+tunes - meas",
            "^-",
        )
        eff_dbety, eff_dbety_err = _rel_diff(
            twiss_eff_online["bety"], twiss_eff_online.get("bety_err"), meas_bety, meas_bety_err
        )
        _plot(
            ax_beta_y,
            meas_twiss.loc[common_bpms, "s"],
            eff_dbety,
            eff_dbety_err,
            "Model+tunes+ests - meas",
            "d-",
        )
        ax_beta_y.axhline(0.0, color="k", linewidth=0.8, alpha=0.5)
        ax_beta_y.set_ylabel("Δ β_y / β_y vs meas (%)")
        ax_beta_y.set_title(f"Arc {arc_num} - Vertical β Δ")
        ax_beta_y.legend(fontsize=8)
        ax_beta_y.grid(visible=True, alpha=0.3)
        ax_beta_y.set_xlabel("S (m)")

        fig.suptitle(
            f"Phase advance & beta comparison - {squeeze_step} - Arc {arc_num} (start: {start_bpm})",
            fontsize=12,
        )
        plt.tight_layout()
        plt.savefig(results_dir / f"phase_advance_{squeeze_step}_arc{arc_num}.png", dpi=150)
    plt.show()


def plot_fullring_comparison(
    accelerator: LHC,
    all_estimates: dict[str, float],
    analysis_dir: Path,
    squeeze_step: str,
    results_dir: Path,
    tune_knobs_file: Path,
    corrector_file: Path | None,
    beam: int,
    deltap: float = 0.0,
) -> None:
    """Plot full-ring optics differences relative to the measurement."""
    meas_twiss, _ = build_twiss_from_measurements(
        analysis_dir, include_errors=True, reverse_bpm_order=beam == 2
    )
    meas_twiss.columns = [col.lower() for col in meas_twiss.columns]

    twiss_basic = get_fullring_twiss(accelerator, deltap=deltap)
    twiss_online = get_fullring_twiss(
        accelerator,
        tune_knobs_file=tune_knobs_file,
        corrector_file=corrector_file,
        deltap=deltap,
    )
    twiss_eff_online = get_fullring_twiss(
        accelerator,
        estimated_magnets=all_estimates,
        tune_knobs_file=tune_knobs_file,
        corrector_file=corrector_file,
        deltap=deltap,
    )
    ip_positions = get_ip_positions(accelerator)

    common_bpms = (
        meas_twiss.index.intersection(twiss_basic.index)
        .intersection(twiss_online.index)
        .intersection(twiss_eff_online.index)
    )
    if len(common_bpms) == 0:
        raise ValueError("No common BPMs found for full-ring comparison.")

    meas_full = meas_twiss.loc[common_bpms].copy()
    base_full = twiss_basic.loc[common_bpms].copy()
    online_full = twiss_online.loc[common_bpms].copy()
    est_full = twiss_eff_online.loc[common_bpms].copy()

    start_bpm = common_bpms[0]
    meas_full = _normalize_phase(meas_full, ("mux", "muy"), start_bpm)
    base_full = _normalize_phase(base_full, ("mux", "muy"), start_bpm)
    online_full = _normalize_phase(online_full, ("mux", "muy"), start_bpm)
    est_full = _normalize_phase(est_full, ("mux", "muy"), start_bpm)

    fig, axes = plt.subplots(2, 2, figsize=(16, 10), sharex=True)
    xvals = meas_full["s"]

    def _diff(model: pd.Series, measurement: pd.Series) -> pd.Series:
        return model - measurement

    def _rel_diff(model: pd.Series, measurement: pd.Series) -> pd.Series:
        return (model - measurement) / measurement * 100.0

    series_to_plot = [
        ("Base model - meas", base_full, "s-", 1.0),
        ("Model+tunes - meas", online_full, "^-", 1.0),
        ("Model+tunes+ests - meas", est_full, "d-", 1.0),
    ]
    plot_specs = [
        (axes[0, 0], "mux", "phase", "Delta mu1 (2pi)"),
        (axes[0, 1], "muy", "phase", "Delta mu2 (2pi)"),
        (axes[1, 0], "betx", "beta", "Delta beta_x / beta_x vs meas (%)"),
        (axes[1, 1], "bety", "beta", "Delta beta_y / beta_y vs meas (%)"),
    ]

    for ax, column, plot_type, ylabel in plot_specs:
        for label, df, fmt, linewidth in series_to_plot:
            if plot_type == "phase":
                yvals = _diff(df[column], meas_full[column])
            else:
                yvals = _rel_diff(df[column], meas_full[column])
            ax.plot(
                xvals,
                yvals,
                fmt,
                markersize=2.5,
                linewidth=linewidth,
                label=label,
                alpha=0.9,
            )
        ax.axhline(0.0, color="k", linewidth=0.8, alpha=0.5)
        ax.set_ylabel(ylabel)
        ax.grid(visible=True, alpha=0.3)
        ax.legend(fontsize=8)
        add_ip_positions_to_plot(ax, ip_positions)

    axes[0, 0].set_title("Full Ring - Horizontal Phase Delta")
    axes[0, 1].set_title("Full Ring - Vertical Phase Delta")
    axes[1, 0].set_title("Full Ring - Horizontal Beta Delta")
    axes[1, 1].set_title("Full Ring - Vertical Beta Delta")
    axes[1, 0].set_xlabel("S (m)")
    axes[1, 1].set_xlabel("S (m)")

    fig.suptitle(
        f"Full-ring optics deltas vs measurement - {squeeze_step} (phase origin: {start_bpm})",
        fontsize=12,
    )
    plt.tight_layout()
    plt.savefig(results_dir / f"phase_advance_{squeeze_step}_fullring.png", dpi=150)

    # Closed-orbit comparison on a separate figure.
    def _pick_orbit_col(df: pd.DataFrame, candidates: tuple[str, ...]) -> str | None:
        for col in candidates:
            if col in df.columns:
                return col
        return None

    x_col = _pick_orbit_col(meas_full, ("x", "orbitx", "cox"))
    y_col = _pick_orbit_col(meas_full, ("y", "orbity", "coy"))

    if x_col is None and y_col is None:
        LOGGER.warning(
            "No closed-orbit columns found in measurement twiss. Skipping full-ring closed-orbit plot."
        )
    else:
        fig_orbit, orbit_axes = plt.subplots(2, 1, figsize=(16, 8), sharex=True)
        orbit_specs = [
            (orbit_axes[0], x_col, "Horizontal closed orbit", "x (m)"),
            (orbit_axes[1], y_col, "Vertical closed orbit", "y (m)"),
        ]

        for ax, col, title, ylabel in orbit_specs:
            if col is None:
                ax.text(
                    0.5,
                    0.5,
                    "Orbit column unavailable in measurement",
                    transform=ax.transAxes,
                    ha="center",
                    va="center",
                )
                ax.set_title(title)
                ax.grid(visible=True, alpha=0.3)
                add_ip_positions_to_plot(ax, ip_positions)
                continue

            ax.plot(
                xvals,
                meas_full[col],
                "o-",
                markersize=2.5,
                linewidth=1.0,
                label="Measurement",
                alpha=0.9,
            )
            ax.plot(
                xvals,
                base_full[col],
                "s-",
                markersize=2.5,
                linewidth=1.0,
                label="Base model",
                alpha=0.9,
            )
            ax.plot(
                xvals,
                online_full[col],
                "^-",
                markersize=2.5,
                linewidth=1.0,
                label="Model+tunes",
                alpha=0.9,
            )
            ax.plot(
                xvals,
                est_full[col],
                "d-",
                markersize=2.5,
                linewidth=1.0,
                label="Model+tunes+ests",
                alpha=0.9,
            )
            ax.set_title(title)
            ax.set_ylabel(ylabel)
            ax.grid(visible=True, alpha=0.3)
            ax.legend(fontsize=8)
            add_ip_positions_to_plot(ax, ip_positions)

        orbit_axes[1].set_xlabel("S (m)")
        fig_orbit.suptitle(
            f"Full-ring closed orbit values - {squeeze_step}",
            fontsize=12,
        )
        plt.tight_layout()
        plt.savefig(results_dir / f"closed_orbit_{squeeze_step}_fullring.png", dpi=150)

    plt.show()


def main():
    """Run the plotting command-line entry point."""
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument("--beam", type=int, choices=[1, 2], required=True, help="Beam number")
    parser.add_argument(
        "--squeeze-step", type=str, required=True, help="Squeeze step, e.g., '1.2m'"
    )
    parser.add_argument(
        "--optics", action="store_true", help="Use the optimisation from optics measurements"
    )
    parser.add_argument(
        "--arcs",
        type=str,
        default=None,
        help="Arcs to plot: can be a range (e.g., '4-6') or comma-separated (e.g., '5,6,7'). If not specified, plots all arcs 1-8.",
    )
    parser.add_argument(
        "--frequency",
        type=str,
        default="0Hz",
        help="Frequency key used to load tune/corrector files (e.g., '0Hz', '+50Hz', '-50Hz').",
    )
    parser.add_argument(
        "--fullring",
        action="store_true",
        help="Plot a single full-ring comparison of mu1, mu2, betax, and betay for the three model cases.",
    )
    args = parser.parse_args()
    beam = args.beam
    squeeze_step = args.squeeze_step
    use_optics = args.optics
    frequency = args.frequency

    # Parse arcs argument
    arc_list = None
    if args.arcs:
        if "-" in args.arcs:
            # Handle range format (e.g., "4-6")
            parts = args.arcs.split("-")
            start, end = int(parts[0]), int(parts[1])
            arc_list = list(range(start, end + 1))
        else:
            # Handle comma-separated format (e.g., "5,6,7")
            arc_list = [int(x.strip()) for x in args.arcs.split(",")]

    beam_path = BETABEAT_DIR / get_measurement_date(squeeze_step) / f"LHCB{beam}/"
    model_base_dir = beam_path / "Models/"
    analysis_base_dir = beam_path / "Results/"

    results_dir = get_results_dir(beam)

    temp_dir = PROJECT_ROOT / "temp_analysis_plots"
    temp_dir.mkdir(exist_ok=True)

    model_dir = model_base_dir / MODEL_DIRS[beam][squeeze_step]
    seq_file = get_or_make_sequence(beam, model_dir)

    fldr_name = "optics" if use_optics else "squeeze"
    estimates_file = PROJECT_ROOT / f"b{beam}_{fldr_name}_results" / f"quad_estimates_{squeeze_step}.txt"
    if not estimates_file.exists():
        print(f"Estimates file not found: {estimates_file}")
        return

    beam_energy, deltap = load_energy_and_deltap_from_metadata(beam, squeeze_step)
    print(f"Beam energy set to: {beam_energy} GeV")

    accelerator = LHC(
        beam=beam,
        beam_energy=beam_energy,
        sequence_file=seq_file,
        optimise_bends=True,
        optimise_quadrupoles=True,
        optimise_other_quadrupoles=True,
        optimise_correctors=False,
        optimise_quad_dx=True,
        optimise_quad_dy=True,
    )

    estimates = load_estimates(estimates_file)
    # Load tune knobs from 0Hz measurement
    tune_knobs_file = results_dir / f"tune_knobs_{squeeze_step}_0Hz.txt"
    if not tune_knobs_file.exists():
        raise FileNotFoundError(f"Tune knobs file not found: {tune_knobs_file}")
    print(f"Using tune knobs file: {tune_knobs_file}")

    corrector_file = results_dir / f"corrector_strengths_{squeeze_step}_{frequency}.txt"
    if not corrector_file.exists():
        raise FileNotFoundError(f"Corrector file not found: {corrector_file}")
    print(f"Using corrector file: {corrector_file}")

    actual = find_true_values(accelerator, estimates, tune_knobs_file)  # , corrector_file)

    plot_quad_diffs(
        estimates,
        actual,
        squeeze_step,
        results_dir,
        fullring=args.fullring,
        accelerator=accelerator if args.fullring else None,
    )

    all_estimates = {}
    for arc in estimates.values():
        all_estimates.update(arc)

    analysis_dir = analysis_base_dir / ANALYSIS_DIRS[beam][squeeze_step]
    if args.fullring:
        plot_fullring_comparison(
            accelerator,
            all_estimates,
            analysis_dir,
            squeeze_step,
            results_dir,
            tune_knobs_file,
            corrector_file,
            beam,
            deltap=deltap,
        )
    else:
        plot_phase_advances(
            accelerator,
            all_estimates,
            analysis_dir,
            squeeze_step,
            results_dir,
            tune_knobs_file,
            corrector_file,
            beam,
            arcs=arc_list,
            deltap=deltap,
        )


if __name__ == "__main__":
    main()
